In [1]:
from RoboticArmEnv import RoboticArmEnv

from robot_descriptions.loaders.mujoco import load_robot_description
# Cargar configuración de Q-learning

# Entrenar el agente
if __name__ == "__main__":
    mdl = load_robot_description("so_arm100_mj_description")
    env = RoboticArmEnv(mdl)
    env.train(episodes=5000)


f:\Python\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
  0%|          | 0/5000 [00:00<?, ?it/s]f:\Python\Lib\site-packages\torch\nn\modules\loss.py:1042: UserWarning: Using a target size (torch.Size([10, 1])) that is different to the input size (torch.Size([10, 6])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)


[ 0.  -0.5  0.   0.  -0.5  0.5]
[ 0.5  0.   0.5 -0.5  0.  -0.5]
[ 0.5 -0.5  0.5  0.5  0.5  0.5]
[-0.5  0.  -0.5  0.5  0.  -0.5]
[ 0.5  0.   0.5  0.5 -0.5  0.5]
[ 0.5  0.5 -0.5 -0.5  0.   0. ]
[ 0.5 -0.5  0.5  0.5  0.5  0.5]
[ 0.   0.   0.5 -0.5 -0.5  0.5]
[ 0.  -0.5 -0.5  0.5  0.5  0. ]
[-0.5  0.5  0.5 -0.5  0.5  0. ]
[ 0.   0.5 -0.5 -0.5 -0.5  0. ]
[ 0.5 -0.5  0.5 -0.5  0.   0.5]
[ 0.  -0.5 -0.5  0.5 -0.5  0. ]
[ 0.   0.5 -0.5 -0.5 -0.5  0. ]
[ 0.5 -0.5  0.5 -0.5 -0.5  0.5]
[ 0.5  0.  -0.5  0.5  0.5  0. ]
[ 0.  -0.5 -0.5 -0.5 -0.5  0.5]
[ 0.  -0.5 -0.5 -0.5 -0.5  0. ]
[ 0.   0.  -0.5 -0.5  0.  -0.5]
[ 0.   0.  -0.5  0.5  0.  -0.5]
[-0.5 -0.5  0.   0.   0.   0.5]
[ 0.   0.5  0.5 -0.5 -0.5 -0.5]
[ 0.  -0.5 -0.5  0.5  0.5  0.5]
[ 0.5  0.5  0.  -0.5  0.5  0.5]
[ 0.  -0.5  0.   0.   0.   0. ]
[-0.5  0.5 -0.5 -0.5  0.   0. ]
[ 0.5  0.  -0.5 -0.5 -0.5  0.5]
[0.  0.5 0.  0.  0.  0. ]
[0.  0.5 0.  0.  0.  0. ]
[0.  0.5 0.  0.  0.  0. ]
[-0.5 -0.5 -0.5  0.  -0.5  0.5]
[ 0.  -0.5  0.  -0.5  0.5 

  0%|          | 0/5000 [01:05<?, ?it/s]

[ 0.  -0.5  0.5  0.5  0.   0.5]
[ 0.   0.5 -0.5 -0.5  0.   0.5]
[ 0.5 -0.5  0.5  0.   0.5  0. ]


KeyboardInterrupt: 